export const CATALOG_SEED = [
  {
    name: "Sour Gummy Mix",
    description: "Tangy fruit gummies",
    priceCents: 250,
    category: "candy" as const,
    imagePath: "/candy/sour-gummy.jpg",
  },
  {
    name: "Chocolate Bar",
    description: "Creamy milk chocolate",
    priceCents: 199,
    category: "candy" as const,
    imagePath: "/candy/chocolate-bar.jpg",
  },
  {
    name: "Rainbow Lollipop",
    description: "Oversized swirl pop",
    priceCents: 125,
    category: "candy" as const,
    imagePath: "/candy/rainbow-lollipop.jpg",
  },
  {
    name: "Peanut Butter Cups",
    description: "Two-pack of cups",
    priceCents: 175,
    category: "candy" as const,
    imagePath: "/candy/peanut-butter-cups.jpg",
  },
  {
    name: "Gummy Worms",
    description: "Sour coated worms",
    priceCents: 225,
    category: "candy" as const,
    imagePath: "/candy/gummy-worms.jpg",
  },
  {
    name: "Hot Chips",
    description: "Spicy crunchy chips",
    priceCents: 150,
    category: "chips" as const,
    imagePath: "/candy/hot-chips.jpg",
  },
  {
    name: "Nacho Cheese Chips",
    description: "Cheesy tortilla chips",
    priceCents: 175,
    category: "chips" as const,
    imagePath: "/candy/nacho-chips.jpg",
  },
  {
    name: "Cheese Puffs",
    description: "Light and cheesy puffs",
    priceCents: 150,
    category: "chips" as const,
    imagePath: "/candy/cheese-puffs.jpg",
  },
  {
    name: "Salted Pretzels",
    description: "Crunchy mini pretzels",
    priceCents: 125,
    category: "chips" as const,
    imagePath: "/candy/pretzels.jpg",
  },
  {
    name: "Orange Soda Bottle",
    description: "Chilled orange soda",
    priceCents: 175,
    category: "drinks" as const,
    imagePath: "/candy/orange-soda.jpg",
  },
  {
    name: "Grape Soda Bottle",
    description: "Chilled grape soda",
    priceCents: 175,
    category: "drinks" as const,
    imagePath: "/candy/grape-soda.jpg",
  },
  {
    name: "Fruit Punch Juice",
    description: "Cold fruit punch",
    priceCents: 150,
    category: "drinks" as const,
    imagePath: "/candy/fruit-punch.jpg",
  },
  {
    name: "Lemonade Cup",
    description: "Fresh squeezed lemonade",
    priceCents: 200,
    category: "drinks" as const,
    imagePath: "/candy/lemonade.jpg",
  },
];

export const SHOP_SEED = [
  {
    shopName: "Ms. Kiki's Snack Spot",
    contactName: "Kiana Roberts",
    neighborhood: "Cherry Hill",
    pickupWindow: "Weekdays, 2:30 PM – 7:00 PM",
    status: "approved" as const,
    photoPath: "/candy/shop-kiki.jpg",
    identityVerified: true,
    stock: {
      "Sour Gummy Mix": 24,
      "Chocolate Bar": 12,
      "Hot Chips": 10,
      "Orange Soda Bottle": 4,
      "Lemonade Cup": 8,
      "Gummy Worms": 6,
    } as Record<string, number>,
  },
  {
    shopName: "Northview Snack Stop",
    contactName: "Jordan Lee",
    neighborhood: "Northview",
    pickupWindow: "Weekdays, 3:00 PM – 6:30 PM",
    status: "approved" as const,
    photoPath: "/candy/shop-northview.jpg",
    identityVerified: true,
    stock: {
      "Rainbow Lollipop": 18,
      "Peanut Butter Cups": 9,
      "Nacho Cheese Chips": 14,
      "Cheese Puffs": 7,
      "Grape Soda Bottle": 11,
      "Fruit Punch Juice": 5,
    } as Record<string, number>,
  },
  {
    shopName: "Eastside Corner Treats",
    contactName: "Marcus Hill",
    neighborhood: "Eastside",
    pickupWindow: "Weekends, 12:00 PM – 8:00 PM",
    status: "pending" as const,
    photoPath: null,
    identityVerified: false,
    stock: {} as Record<string, number>,
  },
];
