window.CANDY_LADY_DATA = {
  source: {
    name: "Open Food Facts",
    url: "https://world.openfoodfacts.org/",
    pulledAt: "2026-08-09",
  },
  sellers: [
    {
      id: "kiki",
      name: "Ms. Kiki's Snack Spot",
      neighborhood: "Cherry Hill",
      pickupTime: "Pickup in 10 minutes",
      rating: 4.9,
      open: true,
      tags: ["Best seller", "Cold drinks", "Approved catalog"],
    },
    {
      id: "coach-t",
      name: "Coach T's Candy Corner",
      neighborhood: "Riverside",
      pickupTime: "Pickup in 15 minutes",
      rating: 4.8,
      open: true,
      tags: ["Candy", "Chips", "Family pick"],
    },
    {
      id: "sunny",
      name: "Sunny Side Sweets",
      neighborhood: "Northview",
      pickupTime: "Opens after 3 PM",
      rating: 4.7,
      open: false,
      tags: ["Gummies", "Sodas", "Weekend pickup"],
    },
  ],
  products: [
    {
      id: "altoids-peppermint",
      barcode: "0022000159335",
      name: "ALTOIDS Curiously Strong Mints Peppermint",
      brand: "Altoids",
      category: "candy",
      categoryLabel: "Candy",
      price: 2.25,
      sellerId: "kiki",
      stock: "in",
      style: "strawberry",
      image: "https://images.openfoodfacts.org/images/products/002/200/015/9335/front_en.15.200.jpg",
      servingSize: "3 pieces (2 g)",
      nutriScore: "N/A",
      novaGroup: 4,
      sugars: "Sugar not listed",
      calories: "14 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0022000159335",
    },
    {
      id: "welchs-fruit-snacks",
      barcode: "0034856890089",
      name: "Fruit Snacks",
      brand: "Welch's",
      category: "candy",
      categoryLabel: "Candy",
      price: 1.75,
      sellerId: "coach-t",
      stock: "low",
      style: "strawberry",
      image: "https://images.openfoodfacts.org/images/products/003/485/689/0089/front_en.40.200.jpg",
      servingSize: "1 pouch (22.7 g)",
      nutriScore: "D",
      novaGroup: 4,
      sugars: "10g sugar",
      calories: "70 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0034856890089",
    },
    {
      id: "peanut-mms",
      barcode: "0040000533214",
      name: "Peanut M&M's Chocolate Candies",
      brand: "M&M's",
      category: "candy",
      categoryLabel: "Candy",
      price: 2.5,
      sellerId: "sunny",
      stock: "in",
      style: "strawberry",
      image: "https://images.openfoodfacts.org/images/products/004/000/053/3214/front_en.32.200.jpg",
      servingSize: "18 pieces (42 g)",
      nutriScore: "E",
      novaGroup: 4,
      sugars: "50g sugar",
      calories: "210 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0040000533214",
    },
    {
      id: "black-forest-gummy-bears",
      barcode: "0041420081309",
      name: "Organic Gummy Bears",
      brand: "Black Forest",
      category: "candy",
      categoryLabel: "Candy",
      price: 2.25,
      sellerId: "kiki",
      stock: "in",
      style: "strawberry",
      image: "https://images.openfoodfacts.org/images/products/004/142/008/1309/front_en.6.200.jpg",
      servingSize: "1 pouch (22 g)",
      nutriScore: "D",
      novaGroup: 4,
      sugars: "11g sugar",
      calories: "70 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0041420081309",
    },
    {
      id: "unreal-coconut-bar",
      barcode: "0857484006482",
      name: "Dark Chocolate Coconut Bar",
      brand: "UNREAL",
      category: "candy",
      categoryLabel: "Candy",
      price: 3.25,
      sellerId: "coach-t",
      stock: "in",
      style: "strawberry",
      image: "https://images.openfoodfacts.org/images/products/085/748/400/6482/front_en.45.200.jpg",
      servingSize: "15 g",
      nutriScore: "D",
      novaGroup: 3,
      sugars: "3g sugar",
      calories: "70 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0857484006482",
    },
    {
      id: "doritos-nacho-cheese",
      barcode: "0028400090211",
      name: "Doritos Nacho Cheese",
      brand: "Doritos",
      category: "chips",
      categoryLabel: "Chips",
      price: 2.25,
      sellerId: "coach-t",
      stock: "in",
      style: "aqua",
      image: "https://images.openfoodfacts.org/images/products/002/840/009/0211/front_en.15.200.jpg",
      servingSize: "1 oz (28 g)",
      nutriScore: "D",
      novaGroup: 4,
      sugars: "1g sugar",
      calories: "150 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0028400090211",
    },
    {
      id: "cheetos-crunchy",
      barcode: "0028400064588",
      name: "Cheetos Crunchy",
      brand: "Cheetos",
      category: "chips",
      categoryLabel: "Chips",
      price: 2,
      sellerId: "kiki",
      stock: "low",
      style: "aqua",
      image: "https://images.openfoodfacts.org/images/products/002/840/006/4588/front_en.22.200.jpg",
      servingSize: "1 oz (28 g)",
      nutriScore: "D",
      novaGroup: 4,
      sugars: "1g sugar",
      calories: "160 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0028400064588",
    },
    {
      id: "lays-classic",
      barcode: "0028400043712",
      name: "Lay's Classic Potato Chips",
      brand: "Lay's",
      category: "chips",
      categoryLabel: "Chips",
      price: 1.75,
      sellerId: "sunny",
      stock: "in",
      style: "aqua",
      image: "https://images.openfoodfacts.org/images/products/002/840/004/3712/front_en.8.200.jpg",
      servingSize: "1 oz (28 g)",
      nutriScore: "C",
      novaGroup: 3,
      sugars: "0g sugar",
      calories: "160 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0028400043712",
    },
    {
      id: "coca-cola-classic",
      barcode: "0049000000019",
      name: "Coca-Cola Classic",
      brand: "Coca-Cola",
      category: "drinks",
      categoryLabel: "Drinks",
      price: 1.75,
      sellerId: "kiki",
      stock: "in",
      style: "citrus",
      image: "https://images.openfoodfacts.org/images/products/004/900/000/0019/front_en.35.200.jpg",
      servingSize: "1 can (355 ml)",
      nutriScore: "E",
      novaGroup: 4,
      sugars: "39g sugar",
      calories: "140 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0049000000019",
    },
    {
      id: "sprite",
      barcode: "0049000028911",
      name: "Sprite Lemon-Lime Soda",
      brand: "Sprite",
      category: "drinks",
      categoryLabel: "Drinks",
      price: 1.75,
      sellerId: "coach-t",
      stock: "in",
      style: "citrus",
      image: "https://images.openfoodfacts.org/images/products/004/900/002/8911/front_en.22.200.jpg",
      servingSize: "1 can (355 ml)",
      nutriScore: "E",
      novaGroup: 4,
      sugars: "38g sugar",
      calories: "140 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0049000028911",
    },
    {
      id: "mountain-dew",
      barcode: "0012000161717",
      name: "Mountain Dew",
      brand: "PepsiCo",
      category: "drinks",
      categoryLabel: "Drinks",
      price: 2,
      sellerId: "sunny",
      stock: "in",
      style: "citrus",
      image: "https://images.openfoodfacts.org/images/products/001/200/016/1717/front_en.15.200.jpg",
      servingSize: "1 can (355 ml)",
      nutriScore: "E",
      novaGroup: 4,
      sugars: "46g sugar",
      calories: "170 cal",
      sourceUrl: "https://world.openfoodfacts.org/product/0012000161717",
    },
  ],
};
